[network]
bind.host = "0.0.0.0"
bind.port = 8080
remote.host = "localhost"
remote.port = 8080

[network.tls]
certificate = "/etc/opendut-network/tls/carl.pem"
key = "/etc/opendut-network/tls/carl.key"

[serve]
ui.directory = "lea/"

[vpn]
enabled = true
kind = ""

[vpn.netbird]
url = ""
https.only = true
auth.type = ""
auth.secret = ""
