# Example configuration file for OpenDuT-CARL in the test environment
[network]
bind.host = "0.0.0.0"
bind.port = 443
remote.host = "carl"
remote.port = 443

[network.tls]
certificate = "/etc/opendut/tls/carl.pem"
key = "/etc/opendut/tls/carl.key"
ca = "/etc/opendut/tls/ca.pem"

[network.oidc]
enabled = true

[network.oidc.client]
client.id = "opendut-carl-client"
client.secret = "6754d533-9442-4ee6-952a-97e332eca38e"
issuer.url = "https://keycloak/realms/opendut/"
issuer.remote.url = "https://keycloak/realms/opendut/"
scopes = ""
# temporary workaround
peer.id = "opendut-edgar-client"
peer.secret = "c7d6ace0-b90f-471a-bb62-a4ecac4150f8"

[network.oidc.lea]
client.id = "opendut-lea-client"
issuer.url = "https://keycloak/realms/opendut/"
scopes = "openid,profile,email"

[serve]
ui.directory = "opendut-lea/"

[vpn]
enabled = true
kind = "netbird"

[vpn.netbird]
url = "https://netbird-management/api"
ca = "/etc/opendut/tls/ca.pem"
auth.type = "personal-access-token"
#auth.secret added dynamically via environment variable

[opentelemetry]
enabled = true
endpoint = "http://otel-collector:4317"
