name: build
on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'LICENSE'

# Required GitHub repository variables:
# https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
# OPENDUT_GH_RUNNER_SMALL: runner labels for small jobs
# OPENDUT_GH_RUNNER_LARGE: runner labels for large jobs

jobs:
  legal:
    uses: ./.github/workflows/legal.yaml
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_SMALL }}"

  generate-sbom:
    uses: ./.github/workflows/sbom.yaml
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_SMALL }}"

  test:
    uses: ./.github/workflows/test.yaml
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-carl:
    uses: ./.github/workflows/build-carl.yaml
    needs: [ test ]
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-edgar:
    uses: ./.github/workflows/build-edgar.yaml
    needs: [ test ]
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-lea:
    uses: ./.github/workflows/build-lea.yaml
    needs: [ test ]
#    with:
#      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"
