name: publish-release
on:
  workflow_dispatch:  # manual trigger
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*  #TODO test flexibility for e.g. v0.1.3-alpha
    - latest  #TODO want this?
    - nightly


# Required GitHub repository variables:
# https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
# OPENDUT_GH_RUNNER_SMALL: runner labels for small jobs
# OPENDUT_GH_RUNNER_LARGE: runner labels for large jobs

jobs:
  legal:
    uses: ./.github/workflows/legal.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_SMALL }}"

  generate-sbom:
    uses: ./.github/workflows/sbom.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_SMALL }}"

  test:
    uses: ./.github/workflows/test.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-carl:
    uses: ./.github/workflows/build-carl.yaml
    needs: [ test ]
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-cleo:
    uses: ./.github/workflows/build-cleo.yaml
    needs: [ test ]
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-edgar:
    uses: ./.github/workflows/build-edgar.yaml
    needs: [ test ]
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  build-lea:
    uses: ./.github/workflows/build-lea.yaml
    needs: [ test ]
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  bundle-edgar:
    needs: [ legal, build-edgar ]
    uses: ./.github/workflows/bundle-edgar.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  bundle-cleo:
    needs: [ legal, build-cleo ]
    uses: ./.github/workflows/bundle-cleo.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"

  bundle-carl:
    needs: [ legal, build-carl, build-lea ]
    uses: ./.github/workflows/bundle-carl.yaml
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_LARGE }}"




  publish-release:  #TODO move into own workflow
    needs: [ bundle-carl, bundle-cleo, bundle-edgar ]
    strategy:
      matrix:
        package:
        - name: opendut-carl
          target:
            name: linux-x86_64  #TODO can be removed?
            triple: x86_64-unknown-linux-gnu
    name: "Build ${{ matrix.package.name }}-${{ matrix.package.target.name }}"
    runs-on: ${{ fromJson(vars.OPENDUT_GH_RUNNER_SMALL) }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3  #TODO commit id
    - uses: ncipollo/release-action@v1 #TODO commit id
      with:
        artifacts: "target/ci/distribution/${{ matrix.package.target.triple }}/*.tar.gz"
#        bodyFile: "body.md"  #TODO RELEASES.md structure

